security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserEntity
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/user/(register|login)
            stateless: true
            json_login:
                check_path: /user/login
                username_path: id
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/(user|order)
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/user/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/get, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/user/delete, roles: ROLE_ADMIN }
        - { path: ^/user/grant, roles: ROLE_ADMIN}
        - { path: ^/user/revoke, roles: ROLE_ADMIN}
        - { path: ^/order/get, roles: [ROLE_ADMIN, ROLE_USER]}