version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony_app
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - symfony_net
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/postgres?serverVersion=16&charset=utf8
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - symfony_net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge
